<?php
        /*
        |--------------------------------------------------------------------------
        | Other system configurations for social API's etc
        |--------------------------------------------------------------------------
        |Define all other custom constants here i.e. Facebook, Twitter etc.
        |
        */
	define('SITE_NAME','');
	define('SITE_EMAIL','');
	define('EMAIL_US','');
	define('PAYPAL_MODE','');
	define('CURRENCY_CODE','GBP');
	define('CURRENCY','');
	define('TAX_RATE','');
	define('CURRENCY_SYMBOL','£');
	define('SMTP_HOST','smtp.gmail.com');
	define('SMTP_PORT','465');
	define('SMTP_MAIL','corephp0@gmail.com');
	define('SMTP_PASSWORD','Sparx@09871');
	define('PAYPAL_BUSINESS','');
	define('FB_LINK','');
	define('TW_LINK','');
	define('SMTP_ENCTYPE','ssl');
	define('VIDEO_LENGTH','');
	define('PAYPAL_URL','');
	define('SANDBOX_URL','');
	define('PAYPAL_CYCLE','');
	define('PAYPAL_TOTALCYCLE','');
	define('PAYPAL_RETURN_URL','');
	define('PAYPAL_NOTIFY_URL','');
	define('PAYPAL_CANCEL_URL','');
	define('PAYPAL_CLIENT_ID','');
	define('PAYPAL_CLIENT_SECRET','');
	define('API_ENDPOINT_A','');
	define('API_ENDPOINT_B','');
	define('API_USERNAME','');
	define('API_PASSWORD','');
	define('API_SIGNATURE','');
?>